;;; magnus-lifecycle-tests.el --- Lifecycle ownership tests -*- lexical-binding: t -*-

(require 'ert)
(require 'cl-lib)
(require 'magnus)
(require 'magnus-attention)
(require 'magnus-coord)

(ert-deftest magnus-initialization-failure-unwinds-partial-setup ()
  (let ((magnus--initialized nil)
        (magnus--restart-required nil)
        (kill-emacs-hook nil)
        (teardowns nil)
        (continued nil))
    (cl-letf
        (((symbol-function 'require) (lambda (&rest _arguments) t))
         ((symbol-function 'magnus--migrate-data-files) #'ignore)
         ((symbol-function 'magnus-persistence-load) #'ignore)
         ((symbol-function 'magnus--agents-index-load) #'ignore)
         ((symbol-function 'magnus-background-setup) #'ignore)
         ((symbol-function 'magnus-review-load-all) #'ignore)
         ((symbol-function 'magnus-persistence--setup-autosave) #'ignore)
         ((symbol-function 'magnus-review-controller-setup) #'ignore)
         ((symbol-function 'magnus-coord-ensure-watchers) #'ignore)
         ((symbol-function 'magnus-context-setup-hooks) #'ignore)
         ((symbol-function 'magnus-attention-setup-hooks) #'ignore)
         ((symbol-function 'magnus-attention-start) #'ignore)
         ((symbol-function 'magnus-coord-start-reminders) #'ignore)
         ((symbol-function 'magnus-health-start)
          (lambda () (error "simulated startup failure")))
         ((symbol-function 'magnus-coord-attention-load)
          (lambda () (setq continued t)))
         ((symbol-function 'magnus-coord-setup-attention-tracking)
          (lambda () (setq continued t)))
         ((symbol-function 'magnus-review-controller-shutdown)
          (lambda () (push 'review teardowns)))
         ((symbol-function 'magnus-status-shutdown)
          (lambda () (push 'status teardowns)))
         ((symbol-function 'magnus-trace-stop-timer)
          (lambda () (push 'trace teardowns)))
         ((symbol-function 'magnus-coord-shutdown)
          (lambda () (push 'coord teardowns)))
         ((symbol-function 'magnus-health-shutdown)
          (lambda () (push 'health teardowns)))
         ((symbol-function 'magnus-background-shutdown)
          (lambda () (push 'background teardowns)))
         ((symbol-function 'magnus-attention-shutdown)
          (lambda () (push 'attention teardowns)))
         ((symbol-function 'magnus-context-shutdown)
          (lambda () (push 'context teardowns)))
         ((symbol-function 'magnus-persistence-shutdown)
          (lambda () (push 'persistence teardowns)))
         ((symbol-function 'message) (lambda (&rest _arguments))))
      (should-error (magnus--ensure-initialized) :type 'error))
    (should-not magnus--initialized)
    (should-not continued)
    (should
     (equal (nreverse teardowns)
            '(review status trace coord health background
                     attention context persistence)))
    (should-not (memq #'magnus--shutdown kill-emacs-hook))))

(ert-deftest magnus-shutdown-continues-after-subsystem-failure ()
  "Every teardown runs even when an earlier subsystem raises an error."
  (let ((magnus--initialized t)
        (calls nil)
        (kill-emacs-hook nil))
    (add-hook 'kill-emacs-hook #'magnus--shutdown)
    (cl-letf
        (((symbol-function 'magnus-review-controller-shutdown)
          (lambda ()
            (push 'review calls)
            (error "simulated teardown failure")))
         ((symbol-function 'magnus-status-shutdown)
          (lambda () (push 'status calls)))
         ((symbol-function 'magnus-trace-stop-timer)
          (lambda () (push 'trace calls)))
         ((symbol-function 'magnus-coord-shutdown)
          (lambda () (push 'coord calls)))
         ((symbol-function 'magnus-health-shutdown)
          (lambda () (push 'health calls)))
         ((symbol-function 'magnus-background-shutdown)
          (lambda () (push 'background calls)))
         ((symbol-function 'magnus-attention-shutdown)
          (lambda () (push 'attention calls)))
         ((symbol-function 'magnus-context-shutdown)
          (lambda () (push 'context calls)))
         ((symbol-function 'magnus-persistence-shutdown)
          (lambda () (push 'persistence calls)))
         ((symbol-function 'message) (lambda (&rest _arguments))))
      (magnus--shutdown))
    (should
     (equal (nreverse calls)
            '(review status trace coord health background
                     attention context persistence)))
    (should-not magnus--initialized)
    (should-not (memq #'magnus--shutdown kill-emacs-hook))))

(ert-deftest magnus-attention-shutdown-releases-owned-state ()
  (let ((magnus-attention-queue '("agent"))
        (magnus-attention-current "agent")
        (magnus-attention--checking t)
        (magnus-attention--monitoring-active t)
        (magnus-attention--timer (run-at-time 3600 nil #'ignore))
        (magnus-attention--focus-timer (run-at-time 3600 nil #'ignore))
        (magnus-instances-changed-hook nil))
    (add-hook 'magnus-instances-changed-hook
              #'magnus-attention--on-instances-empty)
    (cl-letf (((symbol-function 'message) (lambda (&rest _arguments))))
      (magnus-attention-shutdown))
    (should-not magnus-attention--timer)
    (should-not magnus-attention--focus-timer)
    (should-not magnus-attention-queue)
    (should-not magnus-attention-current)
    (should-not magnus-attention--checking)
    (should-not magnus-attention--monitoring-active)
    (should-not (memq #'magnus-attention--on-instances-empty
                      magnus-instances-changed-hook))))

(ert-deftest magnus-coord-shutdown-releases-watchers-hooks-and-saves ()
  (let* ((poll (run-at-time 3600 nil #'ignore))
         (reminder (run-at-time 3600 nil #'ignore))
         (idle (run-at-time 3600 nil #'ignore))
         (presence-retry (run-at-time 3600 nil #'ignore))
         (save (run-at-time 3600 nil #'ignore))
         (magnus-coord--poll-timer poll)
         (magnus-coord--reminder-timer reminder)
         (magnus-coord--idle-timer idle)
         (magnus-coord--presence-retry-timer presence-retry)
         (magnus-coord--presence-states (make-hash-table :test 'equal))
         (magnus-coord--attention-save-timer save)
         (magnus-coord--watched-dirs '("/tmp/project"))
         (magnus-coord--file-mtimes '(("/tmp/project" . 1)))
         (magnus-coord--processed-mentions '(("/tmp/project" . ("x"))))
         (magnus-coord--processed-dms '(("/tmp/project" . ("x"))))
         (magnus-coord--processed-summons '(("/tmp/project" . ("x"))))
         (window-buffer-change-functions nil)
         (pre-command-hook nil)
         (magnus-instances-changed-hook nil)
         (saves 0))
    (puthash "agent" (list :desired 'away :delivered 'back)
             magnus-coord--presence-states)
    (add-hook 'window-buffer-change-functions #'magnus-coord--on-buffer-focus)
    (add-hook 'pre-command-hook #'magnus-coord--on-user-return)
    (add-hook 'magnus-instances-changed-hook
              #'magnus-coord--on-presence-instances-changed)
    (cl-letf (((symbol-function 'magnus-coord-attention-save)
               (lambda () (cl-incf saves))))
      (magnus-coord-shutdown))
    (should (= saves 1))
    (should-not magnus-coord--poll-timer)
    (should-not magnus-coord--reminder-timer)
    (should-not magnus-coord--idle-timer)
    (should-not magnus-coord--presence-retry-timer)
    (should (zerop (hash-table-count magnus-coord--presence-states)))
    (should-not magnus-coord--attention-save-timer)
    (should-not magnus-coord--watched-dirs)
    (should-not magnus-coord--file-mtimes)
    (should-not magnus-coord--processed-mentions)
    (should-not magnus-coord--processed-dms)
    (should-not magnus-coord--processed-summons)
    (should-not (memq #'magnus-coord--on-buffer-focus
                      window-buffer-change-functions))
    (should-not (memq #'magnus-coord--on-user-return pre-command-hook))
    (should-not
     (memq #'magnus-coord--on-presence-instances-changed
           magnus-instances-changed-hook))))

(provide 'magnus-lifecycle-tests)
;;; magnus-lifecycle-tests.el ends here
