;;; magnus-coord-presence-tests.el --- Presence coalescing tests -*- lexical-binding: t -*-

(require 'ert)
(require 'cl-lib)
(require 'magnus-coord)

(defun magnus-coord-presence-tests--instance (id &optional provider)
  "Return a running interactive test instance named by ID and PROVIDER."
  (magnus-instance--create
   :id id :name id :directory temporary-file-directory
   :provider (or provider 'claude) :status 'running :kind 'interactive))

(defmacro magnus-coord-presence-tests--isolated (instances &rest body)
  "Run BODY with presence state isolated around INSTANCES."
  (declare (indent 1) (debug (form body)))
  `(let ((magnus-instances ,instances)
         (magnus-coord--presence-states (make-hash-table :test 'equal))
         (magnus-coord--presence-retry-timer nil)
         (magnus-coord--presence-attempt-sequence 0)
         (magnus-coord--presence-retry-delay 3600)
         (magnus-coord--user-idle-p nil)
         (magnus-coord--idle-timer nil)
         (magnus-coord-idle-threshold nil)
         (pre-command-hook nil))
     (unwind-protect
         (progn ,@body)
       (magnus-coord--stop-presence-retries))))

(ert-deftest magnus-coord-quiescence-resets-for-replacement-runtime ()
  "A fresh TUI cannot inherit an old runtime's quiet timestamp."
  (let* ((old-buffer (generate-new-buffer " *magnus-quiet-old*"))
         (old-process
          (make-pipe-process :name "magnus-quiet-old"
                             :buffer old-buffer :noquery t))
         (new-buffer (generate-new-buffer " *magnus-quiet-new*"))
         (new-process
          (make-pipe-process :name "magnus-quiet-new"
                             :buffer new-buffer :noquery t))
         (instance (magnus-coord-presence-tests--instance "quiet"))
         (magnus-instances (list instance))
         (magnus-coord--buffer-ticks (make-hash-table :test 'equal))
         (magnus-coord-quiescence-threshold 30))
    (setf (magnus-instance-buffer instance) old-buffer)
    (unwind-protect
        (progn
          (should (= (buffer-modified-tick old-buffer)
                     (buffer-modified-tick new-buffer)))
          (magnus-coord--update-buffer-ticks)
          (let ((record (gethash "quiet" magnus-coord--buffer-ticks)))
            (setq record (plist-put record :changed-at 0))
            (puthash "quiet" record magnus-coord--buffer-ticks))
          (should (magnus-coord-agent-quiescent-p instance))
          (setf (magnus-instance-buffer instance) new-buffer)
          (magnus-coord--update-buffer-ticks)
          (let ((record (gethash "quiet" magnus-coord--buffer-ticks)))
            (should (eq (plist-get record :buffer) new-buffer))
            (should (eq (plist-get record :process) new-process)))
          (should-not (magnus-coord-agent-quiescent-p instance)))
      (dolist (process (list old-process new-process))
        (when (process-live-p process)
          (delete-process process)))
      (dolist (buffer (list old-buffer new-buffer))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest magnus-coord-presence-undelivered-contradiction-disappears ()
  "Away followed by back owns no terminal input when submission declined."
  (let ((instance (magnus-coord-presence-tests--instance "selected"))
        attempts accepted)
    (magnus-coord-presence-tests--isolated (list instance)
      (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                ((symbol-function 'magnus-coord-agent-busy-p)
                 (lambda (_instance) nil))
                ((symbol-function 'magnus-coord-agent-quiescent-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-coord--instance-running-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-process--ensure-agent-dir) #'ignore)
                ((symbol-function 'magnus-coord--try-presence-submit)
                 (lambda (_instance text receipt)
                   (push text attempts)
                   (setq accepted receipt)
                   nil)))
        (magnus-coord--on-user-idle)
        (should (= (length attempts) 1))
        (should (functionp accepted))
        (should (= (hash-table-count magnus-coord--presence-states) 1))
        (magnus-coord--on-user-return)
        (should (zerop (hash-table-count magnus-coord--presence-states)))
        (should-not magnus-coord--presence-retry-timer)))))

(ert-deftest magnus-coord-presence-delivers-one-away-and-one-back ()
  "Accepted presence changes deduplicate and preserve required ordering."
  (let ((instance (magnus-coord-presence-tests--instance "awake"))
        delivered)
    (magnus-coord-presence-tests--isolated (list instance)
      (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                ((symbol-function 'magnus-coord-agent-busy-p)
                 (lambda (_instance) nil))
                ((symbol-function 'magnus-coord-agent-quiescent-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-coord--instance-running-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-process--ensure-agent-dir) #'ignore)
                ((symbol-function 'magnus-coord--try-presence-submit)
                 (lambda (_instance text receipt)
                   (push text delivered)
                   (funcall receipt)
                   'submitted)))
        (magnus-coord--on-user-idle)
        (magnus-coord--on-user-idle)
        (should (= (length delivered) 1))
        (should-not magnus-coord--presence-retry-timer)
        (magnus-coord--on-user-return)
        ;; Return hooks only alter desired state; they never write into the
        ;; terminal composer before the user's triggering key is handled.
        (should (= (length delivered) 1))
        (magnus-coord--flush-presence)
        (should (= (length delivered) 2))
        (should (string-match-p "user is away" (cadr delivered)))
        (should (string-match-p "user is back" (car delivered)))
        (should (zerop (hash-table-count magnus-coord--presence-states)))))))

(ert-deftest magnus-coord-presence-partial-away-is-compensated-after-return ()
  "A pasted away whose Return lands late is followed by exactly one back."
  (let ((instance (magnus-coord-presence-tests--instance "partial"))
        away-receipt delivered)
    (magnus-coord-presence-tests--isolated (list instance)
      (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                ((symbol-function 'magnus-coord-agent-busy-p)
                 (lambda (_instance) nil))
                ((symbol-function 'magnus-coord-agent-quiescent-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-coord--instance-running-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-process--ensure-agent-dir) #'ignore)
                ((symbol-function 'magnus-coord--try-presence-submit)
                 (lambda (_instance text receipt)
                   (push text delivered)
                   (if away-receipt
                       (progn (funcall receipt) 'submitted)
                     (setq away-receipt receipt)
                     'queued))))
        (magnus-coord--on-user-idle)
        (magnus-coord--on-user-return)
        (should (= (length delivered) 1))
        (funcall away-receipt)
        (magnus-coord--flush-presence)
        (should (= (length delivered) 2))
        (should (string-match-p "user is back" (car delivered)))
        (should (zerop (hash-table-count magnus-coord--presence-states)))))))

(ert-deftest magnus-coord-presence-second-away-absorbs-pending-back ()
  "A new away before an accepted back requires no redundant transition."
  (let ((instance (magnus-coord-presence-tests--instance "cycling"))
        away-receipt delivered)
    (magnus-coord-presence-tests--isolated (list instance)
      (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                ((symbol-function 'magnus-coord-agent-busy-p)
                 (lambda (_instance) nil))
                ((symbol-function 'magnus-coord-agent-quiescent-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-coord--instance-running-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-process--ensure-agent-dir) #'ignore)
                ((symbol-function 'magnus-coord--try-presence-submit)
                 (lambda (_instance text receipt)
                   (push text delivered)
                   (setq away-receipt receipt)
                   'queued)))
        (magnus-coord--on-user-idle)
        (magnus-coord--on-user-return)
        (magnus-coord--on-user-idle)
        (funcall away-receipt)
        (magnus-coord--flush-presence)
        (should (= (length delivered) 1))
        (let ((record (gethash "cycling" magnus-coord--presence-states)))
          (should (eq (plist-get record :desired) 'away))
          (should (eq (plist-get record :delivered) 'away))
          (should-not (plist-get record :attempt)))))))

(ert-deftest magnus-coord-presence-transitions-are-per-agent ()
  "Only an agent that accepted away receives the corresponding back."
  (let ((accepted (magnus-coord-presence-tests--instance "accepted"))
        (declined (magnus-coord-presence-tests--instance "declined"))
        deliveries)
    (magnus-coord-presence-tests--isolated (list accepted declined)
      (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                ((symbol-function 'magnus-coord-agent-busy-p)
                 (lambda (_instance) nil))
                ((symbol-function 'magnus-coord-agent-quiescent-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-coord--instance-running-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-process--ensure-agent-dir) #'ignore)
                ((symbol-function 'magnus-coord--try-presence-submit)
                 (lambda (instance text receipt)
                   (push (cons (magnus-instance-id instance) text) deliveries)
                   (when (string= (magnus-instance-id instance) "accepted")
                     (funcall receipt)
                     'submitted))))
        (magnus-coord--on-user-idle)
        (magnus-coord--on-user-return)
        (magnus-coord--flush-presence)
        (should (= (cl-count "accepted" deliveries :key #'car :test #'equal) 2))
        (should (= (cl-count "declined" deliveries :key #'car :test #'equal) 1))
        (should (zerop (hash-table-count magnus-coord--presence-states)))))))

(ert-deftest magnus-coord-presence-old-runtime-receipt-cannot-win ()
  "A receipt from a replaced terminal cannot accept its successor's state."
  (let* ((old-buffer (generate-new-buffer " *magnus-presence-old*"))
         (old-process
          (make-pipe-process :name "magnus-presence-old"
                             :buffer old-buffer :noquery t))
         (new-buffer (generate-new-buffer " *magnus-presence-new*"))
         (new-process
          (make-pipe-process :name "magnus-presence-new"
                             :buffer new-buffer :noquery t))
         (instance (magnus-coord-presence-tests--instance "replacement"))
         receipts)
    (setf (magnus-instance-buffer instance) old-buffer)
    (unwind-protect
        (magnus-coord-presence-tests--isolated (list instance)
          (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks)
                     #'ignore)
                    ((symbol-function 'magnus-coord-agent-busy-p)
                     (lambda (_instance) nil))
                    ((symbol-function 'magnus-coord-agent-quiescent-p)
                     (lambda (_instance) t))
                    ((symbol-function 'magnus-coord--instance-running-p)
                     (lambda (_instance) t))
                    ((symbol-function 'magnus-process--ensure-agent-dir)
                     #'ignore)
                    ((symbol-function 'magnus-coord--try-presence-submit)
                     (lambda (_instance _text receipt)
                       (setq receipts (append receipts (list receipt)))
                       'queued)))
            (magnus-coord--on-user-idle)
            (should (= (length receipts) 1))
            (setf (magnus-instance-buffer instance) new-buffer)
            (magnus-coord--flush-presence)
            (should (= (length receipts) 2))
            (funcall (car receipts))
            (let ((record
                   (gethash "replacement" magnus-coord--presence-states)))
              (should (eq (plist-get record :delivered) 'back))
              (should (plist-get record :attempt)))
            (funcall (cadr receipts))
            (let ((record
                   (gethash "replacement" magnus-coord--presence-states)))
              (should (eq (plist-get record :delivered) 'away))
              (should-not (plist-get record :attempt)))))
      (dolist (process (list old-process new-process))
        (when (process-live-p process)
          (delete-process process)))
      (dolist (buffer (list old-buffer new-buffer))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest magnus-coord-presence-retries-without-coordination-watcher ()
  "Pending latest-state delivery owns its own bounded retry timer."
  (let ((instance (magnus-coord-presence-tests--instance "timer")))
    (magnus-coord-presence-tests--isolated (list instance)
      (let ((magnus-coord--watched-dirs nil))
        (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                  ((symbol-function 'magnus-coord-agent-busy-p)
                   (lambda (_instance) nil))
                  ((symbol-function 'magnus-coord-agent-quiescent-p)
                   (lambda (_instance) nil)))
          (magnus-coord--on-user-idle)
          (should (timerp magnus-coord--presence-retry-timer)))))))

(ert-deftest magnus-coord-presence-hard-failure-parks-until-transition ()
  "A persistent local error is logged once rather than every retry tick."
  (let ((instance (magnus-coord-presence-tests--instance "parked"))
        (attempts 0))
    (magnus-coord-presence-tests--isolated (list instance)
      (cl-letf (((symbol-function 'magnus-coord--update-buffer-ticks) #'ignore)
                ((symbol-function 'magnus-coord-agent-busy-p)
                 (lambda (_instance) nil))
                ((symbol-function 'magnus-coord-agent-quiescent-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-coord--instance-running-p)
                 (lambda (_instance) t))
                ((symbol-function 'magnus-process--ensure-agent-dir)
                 (lambda (_instance)
                   (cl-incf attempts)
                   (error "read-only memory home")))
                ((symbol-function 'message) #'ignore))
        (magnus-coord--on-user-idle)
        (let ((record (gethash "parked" magnus-coord--presence-states)))
          (should (eq (plist-get record :parked) 'away)))
        (should-not magnus-coord--presence-retry-timer)
        (magnus-coord--flush-presence)
        (should (= attempts 1))
        (magnus-coord--on-user-return)
        (should (zerop (hash-table-count magnus-coord--presence-states)))))))

(ert-deftest magnus-coord-presence-does-not-use-durable-nudge-fifo ()
  "Replaceable state uses try-submit while ordinary nudges remain untouched."
  (let ((instance (magnus-coord-presence-tests--instance "transport"))
        submission)
    (cl-letf (((symbol-function 'magnus-terminal-try-submit)
               (lambda (&rest arguments)
                 (setq submission arguments)
                 nil))
              ((symbol-function 'magnus-terminal-submit)
               (lambda (&rest _arguments)
                 (ert-fail "presence entered the durable coordination FIFO"))))
      (magnus-coord--try-presence-submit instance "away" #'ignore)
      (should (eq (car submission) instance))
      (should (equal (cadr submission) "[From Magnus]: away"))
      (should (equal (plist-get (cddr submission) :accepted) #'ignore)))))

(ert-deftest magnus-coord-presence-preserves-legacy-adapter-support ()
  "An older vterm adapter without `try-send' uses generic ephemeral ingress."
  (let ((instance
         (magnus-coord-presence-tests--instance "legacy-adapter" 'custom))
        submission)
    (cl-letf (((symbol-function 'magnus-provider-external-p)
               (lambda (_instance) t))
              ((symbol-function 'magnus-provider-operation-p)
               (lambda (_instance _operation) nil))
              ((symbol-function 'magnus-provider-call)
               (lambda (&rest _arguments)
                 (ert-fail "legacy adapter was sent an unknown operation")))
              ((symbol-function 'magnus-terminal-try-submit)
               (lambda (&rest arguments)
                 (setq submission arguments)
                 nil)))
      (magnus-coord--try-presence-submit instance "away" #'ignore)
      (should (eq (car submission) instance))
      (should (equal (cadr submission) "[From Magnus]: away")))))

(provide 'magnus-coord-presence-tests)
;;; magnus-coord-presence-tests.el ends here
